package GUI;


/**
 *
 * @author Jedidian
 */

public class Main extends javax.swing.JFrame {
    /* 0 y 1 -> Parentesis
    * 2 y 4 -> Operadores
    * 5 y 6 -> Operandos
    * 7 -> fin de linea ... ;
    */
    String symAB = "()*|ab;"; // Tipo 1: Numerica
    String sym01 = "()*|01;"; // Tipo 2: Alfabetica
    
                   
    boolean existe0, existe1, existeA, existeB;
    int valor0, valor1, valorA, valorB;
    /**
     * Creates new form Login
     */
    public Main() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Btn_salir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Txt_string = new javax.swing.JTextField();
        Btn_limpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtA_caracteres = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtA_cadena = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_tipo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        Btn_salir.setText("Salir");
        Btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_salirActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Insertar Cadena: ");

        Txt_string.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_stringActionPerformed(evt);
            }
        });
        Txt_string.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_stringKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Txt_stringKeyReleased(evt);
            }
        });

        Btn_limpiar.setText("Limpiar");
        Btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_limpiarActionPerformed(evt);
            }
        });

        TxtA_caracteres.setColumns(20);
        TxtA_caracteres.setRows(5);
        jScrollPane1.setViewportView(TxtA_caracteres);

        jLabel2.setText("Aviso sobre Caracteres: ");

        TxtA_cadena.setColumns(20);
        TxtA_cadena.setRows(5);
        jScrollPane2.setViewportView(TxtA_cadena);

        jLabel3.setText("Aviso sobre La cadena: ");

        jLabel4.setText("Tipo de cadena: ");

        lbl_tipo.setForeground(new java.awt.Color(0, 51, 255));
        lbl_tipo.setText(" ...");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbl_tipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(159, 159, 159)
                                .addComponent(Btn_limpiar))
                            .addComponent(Txt_string))))
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Txt_string, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(Btn_limpiar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lbl_tipo))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Btn_salir))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Btn_salir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_stringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_stringActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_stringActionPerformed

    private void Btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_limpiarActionPerformed
        // TODO add your handling code here:
        Txt_string.setText("");
        TxtA_caracteres.setText("");
        TxtA_cadena.setText("");
    }//GEN-LAST:event_Btn_limpiarActionPerformed

    private void Btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_Btn_salirActionPerformed

    private void Txt_stringKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_stringKeyTyped
        
    }//GEN-LAST:event_Txt_stringKeyTyped

    private void Txt_stringKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_stringKeyReleased
       
        // Codigo al actualizar la cadena
        boolean valida = true;
        int tipo;
        String cadena = Txt_string.getText();
        
        System.out.println("cadena: " + cadena);
        tipo = llenar(cadena);
        
        if( tipo != -1){
            
            if( tipo == 1){
                 System.out.println("tipo de cadena: Numerica");
                 lbl_tipo.setText("0`s y 1`s");
            }else{
                System.out.println("tipo de cadena: alfabetica");
                lbl_tipo.setText("a`s y b`s");
            }
            
        }else{
            System.out.println("Cadena Vacia: " + tipo);
        }
        
       System.out.println(" - - - - - - - - - - ");
        
        valida = evaluarCadena(cadena, tipo);
        
        if (valida == true) {
            TxtA_cadena.setText("Cadena Valida");
        } else {
            TxtA_cadena.setText("Cadena  Invalida");
        }
  
    }//GEN-LAST:event_Txt_stringKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_limpiar;
    private javax.swing.JButton Btn_salir;
    private javax.swing.JTextArea TxtA_cadena;
    private javax.swing.JTextArea TxtA_caracteres;
    private javax.swing.JTextField Txt_string;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_tipo;
    // End of variables declaration//GEN-END:variables

    public boolean evaluarCadena(String cadena, int tipo) {
        
        String simbolos = "";
        
        //Cadena numerica
        if(tipo == 1){
            System.out.println("Validacion de cadena numerica");
            simbolos = sym01;
        }//Cadena alfabetica
        else{
            System.out.println("Validacion de cadena numerica");
            simbolos = symAB;
        }
        
        boolean valido = true;
        
        if( !cadena.equalsIgnoreCase("") ){
        
            String nuevo = "";
            boolean encontrado = false;
            
            for (int i = 0; i < cadena.length(); i++) {
                
                char c = cadena.charAt(i) ;
                String actual = "";
           
                int pos = simbolos.indexOf( c );
                
                if( pos != -1){
                    actual = c + " -> caracter valido \n";
                    encontrado = true;
                }else{
                    actual = c + " -> caracter NO valido \n";
                    encontrado = true;
                    valido = false;
                }
                
                nuevo = nuevo + actual + "\n";
                TxtA_caracteres.setText( nuevo );
            }
        
        }else{
            TxtA_cadena.setText("La cadena esta vacia ...");
        }
        
        return valido;
    }
   
   public int llenar( String cadena ){
       
       int tipo = -1;
       //Llenado de Valores numericos de cada Operador
       valor0 = cadena.indexOf('0') ;
       valor1 = cadena.indexOf('1') ;
       valorA = cadena.indexOf('a') ;
       valorB = cadena.indexOf('b') ;
       
       // 0
       if( valor0 != -1){
           existe0 = true;
       }else{
           existe0 = false;
       }
       
       // 1
       if( valor1 != -1){
           existe1 = true;
       }else{
           existe1 = false;
       }
       
       //A
       if( valorA != -1){
           existeA = true;
       }else{
           existeA = false;
       }
       
       // B
       if( valorB != -1){
           existeB = true;
       }else{
           existeB = false;
       }
       System.out.println("existeO: "+ existe0 + " Valor0; " + valor0);
       System.out.println("existe1: "+ existe1 + " Valor1; " + valor1);
       System.out.println("existeA: "+ existeA + " ValorA; " + valorA);
       System.out.println("existeB: "+ existeB + " ValorB; " + valorB);
       
       tipo = revisarValores( existe0, existe1, existeA, existeB);
       
       return tipo;
   }
    
   public int revisarValores(boolean c0, boolean c1, boolean cA, boolean cB){
       int tipo = -1;
       
       //vacio
       if( (c0 ==false) && (c1 ==false) && (cA ==false) && (cB ==false) ){
           tipo = -1;
       }// inicio con A o B
       else if( ((c0 ==false) && (c1 ==false) && (cA ==false) && (cB ==true))  ||
                ((c0 ==false) && (c1 ==false) && (cA ==true) && (cB ==false)) || 
                ((c0 ==false) && (c1 ==false) && (cA ==true) && (cB ==true)) ){
           
           tipo = 2;
           
       }// inicio con 0 o 1 
       else if( ((c0 ==false) && (c1 ==true) && (cA ==false) && (cB ==false))  ||
                ((c0 ==true) && (c1 ==false) && (cA ==false) && (cB ==false)) || 
                ((c0 ==true) && (c1 ==true) && (cA ==false) && (cB ==false)) ){
           
           tipo = 1;
           
       }// Numero vs Letra
       else if(  ((c0 ==false) && (c1 ==true) && (cA ==false) && (cB ==true)) ||
                 ((c0 ==false) && (c1 ==true) && (cA ==true) && (cB ==false)) || 
                 ((c0 ==true) && (c1 ==false) && (cA ==false) && (cB ==true)) || 
                 ((c0 ==true) && (c1 ==false) && (cA ==true) && (cB ==false)) ){
           
           // C1 vs A, B
           if( (c1== true) && (cB == true)){
               System.out.println("Comparacion entre 1 y B");
               tipo = compararNumeroLetra( valor1, valorB );
           }
           else if( (c1== true) && (cA == true)){
               System.out.println("Comparacion entre 1 y A");
               tipo = compararNumeroLetra( valor1, valorA ) ;
           }
           //C0 vs, A,B
           else if( (c0== true) && (cB == true)){
               System.out.println("Comparacion entre 0 y B");
               tipo = compararNumeroLetra( valor0, valorB );
           }
           else if( (c0== true) && (cA == true)){
               System.out.println("Comparacion entre 0 y A");
               tipo = compararNumeroLetra( valor0, valorA );
           }
       }// Numero vs 2Letras
       else if(  ((c0 ==false) && (c1 ==true) && (cA ==true) && (cB ==true)) ||
                 ((c0 ==true) && (c1 ==false) && (cA ==true) && (cB ==true)) ){
           
           // C1 vs A, B
           if( (c1== true) && (cA == true) && (cB == true) ){
               System.out.println("Comparacion entre 1, A y B");
               tipo = compararNumero2Letras( valor1, valorA, valorB );
           }// C0 vs A, B
           else if( (c1== true) && (cA == true) && (cB == true) ){
               System.out.println("Comparacion entre 0, A y B");
               tipo = compararNumero2Letras( valor0, valorA, valorB );
           }
  
       }// Letra vs 2Numeros
       else if(  ((c0 ==true) && (c1 ==true) && (cA ==false) && (cB ==true)) ||
                 ((c0 ==true) && (c1 ==true) && (cA ==true) && (cB ==false)) ){
           
           //B vs C0, C1
           if( (c0== true) && (c1 == true) && (cB == true) ){
               System.out.println("Comparacion entre 1, A y B");
               tipo = compararLerta2Numeros( valorB, valor0, valor1 );
           }//A vs C0, C1
           else if( (c0== true) && (c1 == true) && (cA == true) ){
               System.out.println("Comparacion entre 0, A y B");
               tipo = compararLerta2Numeros( valorA, valor0, valor1 );
           }
  
       }// 2Letras vs 2Numeros
       else if(  ((c0 ==true) && (c1 ==true) && (cA ==true) && (cB ==true)) ){

            System.out.println("Comparacion entre 0, 1, A y B");
            //tipo = compararTodo( valor0, valor1, valorA, valorB );
       }
       
       return tipo;
   }
   
   public int compararNumeroLetra( int numero, int letra){
       int tipo = -1;
       
       if( numero < letra ){
           System.out.println("Empieza con numero");
           tipo = 1;
       }else{
           System.out.println("Empieza con letra");
           tipo = 2;
       }
   
       return tipo;
   }
   
    public int compararNumero2Letras(int numero, int letra1, int letra2) {
        int tipo = -1;

        //nun vs l1
        if ((numero < letra1)) {

            //inicia con numero
            if ((numero < letra2)) {
                System.out.println("inicia con numero");
                tipo = 1;
            }//inicia con letra
            else {
                System.out.println("inicia con letra");
                tipo = 2;
            }
        }//nun vs l2
        else if ((numero < letra2)) {

            //inicia con numero
            if ((numero < letra1)) {
                System.out.println("inicia con numero");
                tipo = 1;
            }//inicia con letra
            else {
                System.out.println("inicia con letra");
                tipo = 2;
            }
        } else {
            System.out.println("inicia con letra");
            tipo = 2;
        }

        return tipo;
    }
    
    public int compararLerta2Numeros(int letra, int num1, int num2) {
        int tipo = -1;

        //l vs num1
        if ((letra < num1)) {

            //inicia con letra
            if ((letra < num2)) {
                System.out.println("inicia con letra");
                tipo = 2;
            }//inicia con letra
            else {
                System.out.println("inicia con numero");
                tipo = 1;
            }
        }//l vs num2
        else if ((letra < num2)) {

            //inicia con letra
            if ((letra < num1)) {
                System.out.println("inicia con letra");
                tipo = 2;
            }//inicia con letra
            else {
                System.out.println("inicia con numero");
                tipo = 1;
            }
        } else {
            System.out.println("inicia con numero");
            tipo = 1;
        }

        return tipo;
    }
    
    
   
//public int compararTodo( int num1, int num2, int letra1 , int letra2 ){
//
//       int tipo = -1;
//
//       //Empieza con numero
//       if( (num1 < letra1) || (num1 < letra2) ||
//           (num2 < letra1) || (num2 < letra2)  ){
//           System.out.println("Empieza con numero");
//           tipo = 1;
//       }//empiza con letra
//       else if( (letra1 < num1) || (letra1 < num2) ||
//                 (letra2 < num1) || (letra2 < num2)  ){
//           System.out.println("Empieza con letra");
//           tipo = 2;
//       }
//   
//       return tipo;
//                
//   }
}
